### ISSUE TITLE
AUR - can't install

### ISSUE THREAD

**Issue by indaleto** [naraesk/plasma-feedreader#1]
On Manjaro KDE with feedreader installed:

Creating plasma5-applets-feedreader...
==> ERROR: changelog must not be an array (portugues->english translation)
==> ERROR: install must not be an array (portugues->english translation)

**Comment by naraesk** [comment]
Thanks, will fix this as soon as possible. But noticed some compilation errors ... projects needs some revision I guess

**Comment by naraesk** [comment]
I.ve updated the package, please try again :)
